import Head from 'next/head'


const index = ():JSX.Element => {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default index
